<a href="https://colab.research.google.com/github/dishankkalra23/Algorithms/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Importing library and creating array

In [ ]:
import numpy as np

x = np.array([1,2,3,4,5])

[1 2 3 4 5]


2. type vs dtype \n
type: type of data structure like list,array,dictionary etc
dtype: data type of data structure 

In [ ]:
print(type(x))
x.dtype

<class 'numpy.ndarray'>


dtype('int64')

3. Creating array with specific data type

In [ ]:
z = np.array([1,2,3],dtype ='f')
print(z)

[1. 2. 3.]


4. Rank of array: for example(x is 1/ 1d array)

In [ ]:
# 1D array:
[1,2,3,4,5]

# 2D array:
[[1,2,3],[4,5,6]]

# 3d array:
[[[1,2,3],[4,5,6]]]

5. shape, size of array

In [ ]:
print(x.shape)
y = np.array([[1,2,5],[3,4,5]])
print("Shape/Dimension:",y.shape)
print("Size: ",y.size)
print("Type of data structure:",type(y))
print("Data type of array:",y.dtype)

(5,)
Shape/Dimension: (2, 3)
Size:  6
Type of data structure: <class 'numpy.ndarray'>
Data type of array: int64


6. Saving numpy array in a file and loading it when it is needed

In [ ]:
arr_name = [1,2,3,4,5]
np.save('file_name',arr_name)
new_arr = np.load('file_name.npy')
print("Saved array:",new_arr)

Saved array: [1 2 3 4 5]


7. Upcasting in numpy: If the array contains elements of different data types and then changing data type to largest data type

In [ ]:
a = np.array([1.2,3.4,4,5,6])
print(a)

[1.2 3.4 4.  5.  6. ]


In [ ]:
import string
list_alphabet = list(string.ascii_lowercase)
alpha = np.array(list_alphabet)
print(alpha)
print(alpha.dtype)
print(type(alpha))
print(alpha.shape)
print(alpha.size)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']
<U1
<class 'numpy.ndarray'>
(26,)
26


In [ ]:
x = np.arange(1,26).reshape(5,5)
x
x[x%2!=0] = -100
x.reshape(5,5)

array([[-100,    2, -100,    4, -100],
       [   6, -100,    8, -100,   10],
       [-100,   12, -100,   14, -100],
       [  16, -100,   18, -100,   20],
       [-100,   22, -100,   24, -100]])

In [ ]:
np.random.randint(1,10,size = (5,5))

array([[8, 1, 6, 6, 7],
       [3, 7, 2, 8, 3],
       [4, 2, 1, 3, 9],
       [9, 6, 9, 5, 9],
       [2, 8, 5, 6, 5]])

In [ ]:
x = np.ones((4,4))*np.array([1,2,3,4]).reshape(1,4)
x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
import pandas as pd
import numpy as np
distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]
planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']
arr = pd.Series(data = distance_from_sun,index = planets)
time = arr/18
time[time]
np.sqrt(distance_from_sun)

array([12.23110788, 37.86159004, 15.09635718, 10.4019229 , 27.90340481])

In [ ]:
import pandas as pd
import numpy as np

x = pd.Series(data=[1,2,3],index=['a','why',2])
x + 2

a      3
why    4
2      5
dtype: int64

In [ ]:
# Pandas Series w/o label
items = {'anay':pd.Series(data=[1,2,3,4,5,[6,7,[8,9,[10,11]]]]),'chaman':pd.Series(data=[1,2,3])}
arr = pd.DataFrame(items)
arr

anay  chaman
0                         1     1.0
1                         2     2.0
2                         3     3.0
3                         4     NaN
4                         5     NaN
5  [6, 7, [8, 9, [10, 11]]]     NaN

In [ ]:
# Array
item2 = {'abc':[1,2,3,4],'def':[5,6,7,8]}
arr2 = pd.DataFrame(item2)
arr2

abc  def
0    1    5
1    2    6
2    3    7
3    4    8

In [ ]:
# Pandas Series with label
items = {'chaman':pd.Series(data=[1,2,3,4,5],index=['a',1,'c',2,'b']),'anay':pd.Series(data=[1,2,3],index=['d','c','a'])}
arr = pd.DataFrame(items)
arr

arr_new = pd.DataFrame(items,index=['a',1,'d'],columns=['chaman'])
arr_new

chaman
a     1.0
1     2.0
d     NaN

In [ ]:
arr = [['a','b','c'],[1,2,3]]
frame = pd.DataFrame(arr,index=['label1','label2'],columns=['alphabet','num1','num2'])
frame

alphabet num1 num2
label1        a    b    c
label2        1    2    3

In [ ]:
new_frame = pd.DataFrame([{'bikes': 20, 'pants': 30, 'watches': 35}, {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5}])

new_frame['glasses'][0] = 0
new_frame['check'] = [1,2]
new_frame


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


bikes  pants  watches  glasses  check
0     20     30       35      0.0      1
1     15      5       10     50.0      2

In [ ]:
import pandas as pd
import numpy as np

arr = [{'k1':[10,20],'k2':3},{'s1':[40,50]}]
a = pd.DataFrame(arr,index=[10,20],columns=['k1','k2','s1'])

a2 = pd.DataFrame([{'k1':0.1,'k2':0.2,'s1':0.5},{'k1':0.2,'k2':0.4,'s1':1}],index=[4,5])
a2

a2 = a2.append(a)
a2['shoda'] = [1,2,3,4]
# print(a2)

x = pd.DataFrame(arr,columns=['k1','k2'],index=[10,20])
x


k1   k2
10  [10, 20]  3.0
20       NaN  NaN

In [ ]:
import pandas as pd

items = [{'bikes': 20, 'pants': 30, 'watches': 35, 'shirts': 15, 'shoes':8, 'suits':45},
{'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5, 'shirts': 2, 'shoes':5, 'suits':7},
{'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4, 'shoes':10}]

df = pd.DataFrame(items,index=['store1','store2','store3'])
print(df,'\n')

df.fillna(method='bfill',axis=1)
df

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('precision', 1)

books = pd.Series(data = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland' ])
authors = pd.Series(data = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', ' H. G. Wells', 'Lewis Carroll' ])
user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8],)
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2])

dictn = {'book':books,'author': authors,'u1':user_1,'u2':user_2,'u3':user_3,'u4':user_4}
df = pd.DataFrame(data=dictn)

dict2 = {'u1':user_1,'u2':user_2,'u3':user_3,'u4':user_4}
df2 = pd.DataFrame(dict2)
arr = np.array(df2.mean(axis=1,skipna=True))


# # print(df)
# # df[(df==5).any(axis=1)]['book'].values


In [ ]:
pd.set_option('precision', 2)
df = pd.read_csv('/Company.csv')
df
print(df)

   Year Name   Dept  Age  Salary
0  1990    A     HR   25      50
1  1990    B     RD   30      48
2  1990    C  Admin   45      55
3  1991    A     HR   26      52
4  1991    B     RD   31      50
5  1991    C  Admin   46      60
6  1992    A     HR   27      60
7  1992    B     RD   32      52
8  1992    C  Admin   47      62


Dept   Year
Admin  1990    55
       1991    60
       1992    62
HR     1990    50
       1991    52
       1992    60
RD     1990    48
       1991    50
       1992    52
Name: Salary, dtype: int64